### ISSUE TITLE
AttributeError: 'TerminalInteractiveShell' object has no attribute 'style'

### ISSUE THREAD

**Issue by melardev** [kmaork/madbg#16]
Hi, I want to report a bug, I am trying to figure out what a stuck pythong script is doing, I gave a try to your module, but unfortunately it crashes with the following stack trace. The server does not have a GUI, it is a plain terminal.

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/madbg/debugger.py", line 124, in start
    yield cls(slave_reader, slave_writer, term_type)
  File "/usr/local/lib/python3.8/dist-packages/madbg/debugger.py", line 30, in __init__
    super().__init__(pt_session_options=dict(input=term_input, output=term_output), stdin=stdin, stdout=stdout)
  File "/usr/local/lib/python3.8/dist-packages/IPython/terminal/debugger.py", line 32, in __init__
    self.pt_init(pt_session_options)
  File "/usr/local/lib/python3.8/dist-packages/IPython/terminal/debugger.py", line 74, in pt_init
    style=self.shell.style,
AttributeError: 'TerminalInteractiveShell' object has no attribute 'style'

Closing connection
```

**Comment by kmaork** [comment]
Hey @melardev , thank you for the report! I have run into this problem before, if I remember correctly it's due to a bug in IPython. IPython decide upon import whether it has a tty, rather than upon invocation. I think this is the relevant issue: https://github.com/ipython/ipython/issues/11745 .
I might try to fix it myself, but until then there's a workaround for you - make sure that when the script you are debugging is initially run, it is run from a terminal.

**Comment by kmaork** [comment]
I have decided to write a workaround. Please try using `madbg=1.1.4` and see if it solves the issue
